trigger:
- master
- main.tf

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: Pay-As-You-Go(d2b83b21-b63f-4c16-a9c4-ee3d9553e497)
  resourceGroup: terraformstorage
  storageAccount: terraformstorage
  container: terrastate
  tfstateFile: myterraform.tfstate
  anyTfChanges: false

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Pay-As-You-Go (d2b83b21-b63f-4c16-a9c4-ee3d9553e497)'
    backendAzureRmResourceGroupName: 'terraformstorage'
    backendAzureRmStorageAccountName: 'terraformstgedemoiac'
    backendAzureRmContainerName: 'terrastate'
    backendAzureRmKey: 'terradeploy.terraform.tfstate'

- task: TerraformTaskV4@4
    inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Pay-As-You-Go (d2b83b21-b63f-4c16-a9c4-ee3d9553e497)'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Pay-As-You-Go (d2b83b21-b63f-4c16-a9c4-ee3d9553e497)'
